/**
 * Design System Manifest (auto-derived from config.ts)
 * ──────────────────────────────────────────────────────
 * Do not edit this file directly — edit src/ds-coverage/config.ts instead.
 *
 * This module derives the runtime data structures the fiber scanner and
 * overlay need from the user-editable config. Importing config here keeps
 * a single source of truth for the component registry.
 */

import config from './config'
import type { DesignDriftConfig } from './types'

export { config }
export type { DesignDriftConfig }

/** Set of all registered DS component names — used by the fiber scanner. */
export const DS_COMPONENTS = new Set<string>(Object.keys(config.components))

/** Set of approved-gap component names — excluded from coverage calculations. */
export const APPROVED_GAPS = new Set<string>(Object.keys(config.approvedGaps ?? {}))

/** Maps component name → Storybook story path (only entries with a storyPath). */
export const DS_STORY_PATHS: Record<string, string> = Object.fromEntries(
  Object.entries(config.components)
    .filter(([, entry]) => entry.storyPath)
    .map(([name, entry]) => [name, entry.storyPath!]),
)

/** Maps component name → Figma node URL (only entries with a figmaLink). */
export const DS_FIGMA_LINKS: Record<string, string> = Object.fromEntries(
  Object.entries(config.components)
    .filter(([, entry]) => entry.figmaLink)
    .map(([name, entry]) => [name, entry.figmaLink!]),
)

/** Resolved Storybook base URL from config (no trailing slash). */
export const STORYBOOK_URL = (config.storybookUrl ?? 'http://localhost:6006').replace(/\/$/, '')

/** CI coverage threshold (0–100). */
export const DRIFT_THRESHOLD = config.threshold ?? 80
