/**
 * SetupWizard — first-run configuration wizard for Drift
 * Supports two paths:
 *   Designer/PM: Figma file key → MCP setup → Dev handoff
 *   Developer:   Storybook URL → select components → export config
 */

import React, { useState, useCallback } from 'react'

// ─── Types ────────────────────────────────────────────────────────────────────

interface StorybookEntry {
  id: string
  title: string
  name: string
}

interface StorybookIndex {
  entries?: Record<string, StorybookEntry>
  stories?: Record<string, StorybookEntry>
}

interface DiscoveredComponent {
  displayName: string
  storyPath: string
}

// Developer steps: 1=persona, 2=sources (multi-select), 'figma'=figma details,
//                  'sb'=storybook URL, 3=select from SB, 4=export, 'manual'=manual entry
// Designer steps:  1=persona, 'd1'=figma, 'd2'=mcp, 'd3'=handoff
type WizardStep = 1 | 2 | 3 | 4 | 'manual' | 'figma' | 'sb' | 'd1' | 'd2' | 'd3'
type DSSource = 'figma' | 'storybook' | 'package' | 'fresh'
type ExportTab = 'config' | 'claude'

// ─── Theme-aware colors ───────────────────────────────────────────────────────

function makeColors(theme: 'dark' | 'light') {
  if (theme === 'light') {
    return {
      bg:      'rgba(253,250,245,0.98)',
      surface: '#f5f0e8',
      border:  'rgba(120,90,40,0.13)',
      text:    '#1a1207',
      muted:   '#7a6a55',
      blue:    '#2563eb',
      green:   '#16a34a',
      orange:  '#d97706',
      red:     '#dc2626',
      purple:  '#7c3aed',
    }
  }
  return {
    bg:      '#09090f',
    surface: '#0f0f18',
    border:  '#1e1e2e',
    text:    '#eeeef4',
    muted:   '#6b6b82',
    blue:    '#4f8ef7',
    green:   '#34d399',
    orange:  '#f59e0b',
    red:     '#ef4444',
    purple:  '#a855f7',
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function extractDisplayName(title: string): string {
  const parts = title.split('/')
  return parts[parts.length - 1].trim()
}

function toIdentifier(name: string): string {
  return name.replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
             .replace(/^[^a-zA-Z]/, '') || name
}

function buildConfigSnippet(
  storybookUrl: string,
  chromaticUrl: string,
  figmaFileKey: string,
  jiraBaseUrl: string,
  jiraProjectKey: string,
  selected: DiscoveredComponent[],
  dsPackage?: string,
): string {
  const lines = [`const config: DesignDriftConfig = {`]
  if (dsPackage) lines.push(`  dsPackages: ['${dsPackage}'],  // run: npm run drift-sync  to auto-fill components`)
  if (storybookUrl) lines.push(`  storybookUrl: '${storybookUrl}',`)
  if (chromaticUrl) lines.push(`  chromaticUrl: '${chromaticUrl}',  // deployed Storybook — public links use this`)
  if (figmaFileKey) lines.push(`  figmaFileKey: '${figmaFileKey}',`)
  if (jiraBaseUrl)  lines.push(`  jiraBaseUrl: '${jiraBaseUrl}',`)
  if (jiraProjectKey) lines.push(`  jiraProjectKey: '${jiraProjectKey}',`)
  lines.push(`  threshold: 80,`)
  lines.push(`  components: {`)
  if (dsPackage && selected.length === 0) {
    lines.push(`    // Auto-populated by drift-sync — run: npm run drift-sync`)
  } else {
    lines.push(`    // Discovered from Storybook`)
    lines.push(...selected.map(c => `    ${toIdentifier(c.displayName)}: { storyPath: '${c.storyPath}' },`))
  }
  lines.push(`  },`)
  lines.push(`}`)
  lines.push(``)
  lines.push(`export default config`)
  return lines.join('\n')
}

function buildClaudeContent(
  selected: DiscoveredComponent[],
  storybookUrl: string,
  chromaticUrl: string,
  figmaFileKey: string,
  hasFigmaMcp: boolean,
): string {
  const tableRows = selected.map(c =>
    `| \`${toIdentifier(c.displayName)}\` | \`${c.storyPath}\` |`
  ).join('\n')
  const sbUrl = chromaticUrl || storybookUrl || 'http://localhost:6006'

  return `# Design System Rules
# Auto-generated by Drift — update when components change

## Source of truth
${figmaFileKey ? `- **Figma file:** https://figma.com/design/${figmaFileKey} — all components are designed here first` : `- **Figma:** ask designer for file key and add to drift.config.ts`}
- **Storybook:** ${sbUrl} — all approved DS components are documented here
- **Tokens:** \`src/tokens/variables.css\` — always use CSS variables, never hardcode values

## The #1 rule: never invent UI from scratch
If a task requires a component not in the list below, do NOT create custom one-off styles.
Instead use a \`<Placeholder>\` and output:
\`\`\`
⚠️  Missing component: [ComponentName]
This needs to be designed in Figma first before it can be built.
Next step: file a design request so it can be added to the component library.
\`\`\`

## Available DS components (always check here first)

| Component | Story Path |
|---|---|
${tableRows}

## Style rules
- **Colors:** \`var(--ds-color-*)\` only — never hardcode hex, rgb, or hsl
- **Spacing:** \`var(--ds-spacing-*)\` — never hardcode px values for margin/padding
- **Border radius:** \`var(--ds-border-radius-*)\`
- **Typography:** Inter, system-ui, sans-serif
- **No CSS files or modules** — inline styles only
- **No new dependencies** without explicit approval

## Figma → Code workflow
1. Designer creates/updates component in Figma
2. \`npm run figma-sync\` pulls tokens → \`src/tokens/variables.css\`
3. Developer builds component in \`src/stories/[ComponentName].tsx\`
4. Add to Storybook + register in \`src/ds-coverage/config.ts\`
5. AI vibe-codes using the registered component — Drift measures coverage
${hasFigmaMcp ? `
## Figma MCP (connected)
You have direct Figma access. When working on components:
- Read existing components: reference the Figma file key \`${figmaFileKey || 'YOUR_FILE_KEY'}\`
- When Drift finds a gap component, use MCP to create the Figma spec directly
- After implementing a component, push a screenshot to the Figma frame for design review
- Token values come from Figma variables — always check figma-sync output matches` : `
## Figma MCP (not connected)
To enable AI-assisted Figma reads and writes, add to your MCP config:
\`\`\`json
{
  "figma": {
    "command": "npx",
    "args": ["-y", "figma-developer-mcp", "--stdio"],
    "env": { "FIGMA_ACCESS_TOKEN": "your-token" }
  }
}
\`\`\`
Get token: figma.com → Profile → Settings → Security → Personal access tokens`}

## Pushing back to Figma
When a custom component has been implemented and approved for the DS:
1. Take a screenshot from the Drift overlay
2. Use \`/drift-push [ComponentName]\` in Claude Code to attach it to the Figma file
3. Run \`npm run figma-sync\` after the Figma component is updated with final tokens
4. Register in \`config.ts\` and update this file

## Drift coverage
- **Threshold:** 80% — CI fails below this
- **Check:** \`npm run drift-check\` locally, or GitHub Actions runs on every PR
- **Fix gaps:** \`/drift fix [ComponentName]\` in Claude Code to auto-migrate
`
}

function buildDevHandoff(figmaKey: string): string {
  const figmaNote = figmaKey ? `\nFigma file key: ${figmaKey} (already added to config)` : ''
  return `Hi! Can you set up Drift on our project? It tracks how much of our UI uses the design system — runs automatically on every PR.

What you need to do:
1. Copy src/ds-coverage/ into the project (or install via npm when available)
2. Add to your app entry point (dev only):
   import { DSCoverageOverlay } from './ds-coverage/DSCoverageOverlay'
   {import.meta.env.DEV && <DSCoverageOverlay />}
3. Connect Storybook URL in src/ds-coverage/config.ts${figmaNote}
4. Push — the GitHub Action at .github/workflows/drift-check.yml runs automatically

Takes about 5 minutes. Full docs: github.com/dyoon92/design-drift`
}

// ─── SetupWizard ─────────────────────────────────────────────────────────────

export interface SetupWizardProps {
  onDone: () => void
  onClose?: () => void
  theme?: 'dark' | 'light'
}

export function SetupWizard({ onDone, onClose, theme = 'dark' }: SetupWizardProps) {
  const C = makeColors(theme)
  const [step, setStep] = useState<WizardStep>(1)

  // Developer path state
  const [sources,      setSources]      = useState<Set<DSSource>>(new Set())
  const [dsPackage,    setDsPackage]    = useState('')
  const [figmaToken,   setFigmaToken]   = useState(() => localStorage.getItem('drift-figma-token') ?? '')
  const [figmaPages,   setFigmaPages]   = useState<string>('')  // freeform page names
  const [figmaCompletion, setFigmaCompletion] = useState<'full' | 'partial' | 'unsure'>('full')
  const [sbCompletion, setSbCompletion] = useState<'full' | 'partial' | 'unsure'>('unsure')
  const [sbUrl, setSbUrl]               = useState('http://localhost:6006')
  const [chromaticUrl, setChromaticUrl] = useState('')
  const [fetching, setFetching]         = useState(false)
  const [fetchErr, setFetchErr]         = useState<string | null>(null)
  const [discovered, setDiscovered]     = useState<DiscoveredComponent[]>([])
  const [selected, setSelected]         = useState<Set<string>>(new Set())
  const [figmaKey, setFigmaKey]         = useState('')
  const [jiraBaseUrl, setJiraBaseUrl]   = useState('')
  const [jiraProjectKey, setJiraProjectKey] = useState('')
  const [hasFigmaMcp, setHasFigmaMcp]   = useState(false)
  const [activeTab, setActiveTab]       = useState<ExportTab>('config')
  const [configCopied, setConfigCopied] = useState(false)
  const [claudeCopied, setClaudeCopied] = useState(false)

  // Designer path state
  const [designerFigmaKey, setDesignerFigmaKey] = useState('')
  const [mcpCopied, setMcpCopied]   = useState(false)
  const [handoffCopied, setHandoffCopied] = useState(false)

  // Manual entry
  const [manualText, setManualText] = useState('')

  // ─── Storybook discovery ────────────────────────────────────────────────

  const handleDiscover = useCallback(async () => {
    setFetching(true)
    setFetchErr(null)
    try {
      const url = sbUrl.replace(/\/$/, '')
      let res: Response
      try {
        res = await fetch(`${url}/index.json`)
      } catch {
        setFetchErr(
          `Can't reach ${url}. Make sure Storybook is running and accessible from this page. ` +
          `If it's on a different port or domain, CORS may be blocking — use manual setup instead.`
        )
        return
      }
      if (res.status === 401 || res.status === 403) {
        setFetchErr(`Storybook returned ${res.status} — it's protected. Use manual setup to enter component names directly.`)
        return
      }
      if (!res.ok) {
        setFetchErr(`Storybook returned HTTP ${res.status}. Check the URL and try again, or use manual setup.`)
        return
      }
      const data: StorybookIndex = await res.json()
      const entries = data.entries ?? data.stories ?? {}
      if (Object.keys(entries).length === 0) {
        setFetchErr(`Connected but found no stories. Make sure your stories are registered and Storybook has finished loading.`)
        return
      }
      const byTitle = new Map<string, string>()
      for (const [id, entry] of Object.entries(entries)) {
        if (!byTitle.has(entry.title)) byTitle.set(entry.title, id)
      }
      const comps: DiscoveredComponent[] = [...byTitle.entries()].map(([title, storyPath]) => ({
        displayName: extractDisplayName(title),
        storyPath,
      }))
      setDiscovered(comps)
      setSelected(new Set(comps.map(c => c.displayName)))
      setStep(3)
    } catch {
      setFetchErr(`Something went wrong parsing the Storybook response. Try manual setup.`)
    } finally {
      setFetching(false)
    }
  }, [sbUrl])

  // ─── Shared UI helpers ──────────────────────────────────────────────────

  const panelStyle: React.CSSProperties = {
    flex: 1, display: 'flex', flexDirection: 'column',
    fontFamily: 'Inter, system-ui, sans-serif', color: C.text,
    background: C.bg, overflow: 'hidden',
  }

  const headerStyle: React.CSSProperties = {
    padding: '12px 14px 10px',
    borderBottom: `1px solid ${C.border}`,
    flexShrink: 0,
    display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8,
  }

  const bodyStyle: React.CSSProperties = {
    flex: 1, overflowY: 'auto', padding: '14px',
  }

  const primaryBtn = (label: string, onClick: () => void, disabled = false): React.ReactElement => (
    <button onClick={onClick} disabled={disabled} style={{
      background: disabled ? C.muted : C.blue,
      color: '#fff', border: 'none', borderRadius: 8,
      padding: '8px 16px', fontSize: 12, fontWeight: 700,
      cursor: disabled ? 'not-allowed' : 'pointer',
      opacity: disabled ? 0.5 : 1,
      fontFamily: 'Inter, system-ui, sans-serif',
    }}>{label}</button>
  )

  const BackBtn = ({ to }: { to: WizardStep }) => (
    <button onClick={() => setStep(to)} style={{
      background: 'none', border: 'none', cursor: 'pointer', padding: 0,
      display: 'inline-flex', alignItems: 'center', gap: 4,
      fontSize: 11, color: C.muted, marginBottom: 6,
      fontFamily: 'Inter, system-ui, sans-serif',
    }}>
      <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
        <path d="M7.5 2L3.5 6l4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
      </svg>
      Back
    </button>
  )

  const CloseBtn = () => onClose ? (
    <button onClick={onClose} style={{
      background: 'none', border: 'none', cursor: 'pointer',
      color: C.muted, fontSize: 16, lineHeight: 1, padding: '2px 4px',
      flexShrink: 0,
    }} title="Close">×</button>
  ) : null

  const numericStep = typeof step === 'number' ? step : 4

  const Progress = ({ total = 4, current = numericStep }: { total?: number; current?: number }) => (
    <div style={{ display: 'flex', alignItems: 'center', gap: 4, padding: '0 14px 10px' }}>
      {Array.from({ length: total }, (_, i) => i + 1).map((n, i) => (
        <React.Fragment key={n}>
          <div style={{
            width: 18, height: 18, borderRadius: '50%',
            background: current >= n ? C.blue : C.border,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 9, fontWeight: 700, color: current >= n ? '#fff' : C.muted,
            transition: 'background 0.2s', flexShrink: 0,
          }}>{n}</div>
          {i < total - 1 && <div style={{ flex: 1, height: 2, background: current > n ? C.blue : C.border, transition: 'background 0.2s' }} />}
        </React.Fragment>
      ))}
    </div>
  )

  // ─── Step 1 — Who are you ───────────────────────────────────────────────

  const Step1 = () => (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <div>
          <div style={{ fontSize: 15, fontWeight: 800, marginBottom: 3 }}>Set up Drift</div>
          <div style={{ fontSize: 12, color: C.muted }}>Who's setting this up?</div>
        </div>
        <CloseBtn />
      </div>
      <div style={{ ...bodyStyle, display: 'flex', flexDirection: 'column', gap: 10 }}>

        <button onClick={() => setStep('d1')} style={{
          background: C.surface, border: `1px solid ${C.border}`, borderRadius: 10,
          padding: '16px 14px', cursor: 'pointer', textAlign: 'center',
          fontFamily: 'Inter, system-ui, sans-serif', transition: 'border-color 0.15s',
        }}
          onMouseEnter={e => (e.currentTarget.style.borderColor = C.purple)}
          onMouseLeave={e => (e.currentTarget.style.borderColor = C.border)}>
          <div style={{ fontSize: 22, marginBottom: 6 }}>◈</div>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 4 }}>I'm a designer or PM</div>
          <div style={{ fontSize: 11, color: C.muted, lineHeight: 1.5 }}>Connect Figma, set up MCP for AI tools, and loop in your developer.</div>
        </button>

        <button onClick={() => setStep(2)} style={{
          background: C.surface, border: `1px solid ${C.border}`, borderRadius: 10,
          padding: '16px 14px', cursor: 'pointer', textAlign: 'left',
          fontFamily: 'Inter, system-ui, sans-serif', transition: 'border-color 0.15s',
        }}
          onMouseEnter={e => (e.currentTarget.style.borderColor = C.blue)}
          onMouseLeave={e => (e.currentTarget.style.borderColor = C.border)}>
          <div style={{ fontSize: 22, marginBottom: 6, textAlign: 'center' }}>⚡</div>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 4, textAlign: 'center' }}>I'm a developer</div>
          <div style={{ fontSize: 11, color: C.muted, lineHeight: 1.5, textAlign: 'center', marginBottom: 10 }}>
            Tell Drift where your components live — it'll set everything up automatically.
          </div>
          <div style={{ fontSize: 10, color: C.blue, background: `${C.blue}10`, border: `1px solid ${C.blue}25`, borderRadius: 6, padding: '6px 10px', lineHeight: 1.6 }}>
            💡 <strong>Using Claude Code?</strong> Run <code style={{ fontFamily: 'monospace' }}>/drift-setup</code> instead — it does everything in ~5 min.
          </div>
        </button>

        <button onClick={() => setStep('manual')} style={{
          background: 'none', border: 'none', cursor: 'pointer', padding: '4px 0',
          fontSize: 11, color: C.muted, fontFamily: 'Inter, system-ui, sans-serif', textAlign: 'center',
        }}>
          I'll type my component names in myself →
        </button>
      </div>
    </div>
  )

  // ─── Step 2 — Where is your DS? (multi-source) ──────────────────────────

  const toggleSource = (s: DSSource) => setSources(prev => {
    const next = new Set(prev)
    next.has(s) ? next.delete(s) : next.add(s)
    return next
  })

  // ─── Designer Step D1 — Figma file ──────────────────────────────────────

  const StepD1 = () => (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <div><BackBtn to={1} />
          <div style={{ fontSize: 14, fontWeight: 800, marginBottom: 3 }}>Your Figma is the source of truth</div>
          <div style={{ fontSize: 12, color: C.muted, lineHeight: 1.5 }}>Drift links every gap component back to Figma so your team knows exactly what needs to be designed.</div>
        </div>
        <CloseBtn />
      </div>
      <Progress total={3} current={1} />
      <div style={{ ...bodyStyle, display: 'flex', flexDirection: 'column', gap: 14 }}>
        <div style={{
          background: C.surface, border: `1px solid ${C.border}`,
          borderRadius: 10, padding: '12px 14px',
          fontSize: 11, color: C.muted, lineHeight: 1.7,
        }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: C.text, marginBottom: 6 }}>◈ What Drift does with Figma</div>
          • When a custom component is detected, Drift links to the Figma file so your developer can find the right design<br/>
          • AI tools with Figma MCP can read your components and recreate them accurately<br/>
          • The "Create in Figma" prompt uses your file as the target
        </div>

        <div>
          <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: C.muted, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 }}>
            Figma file key <span style={{ color: C.muted, fontWeight: 400 }}>(optional but recommended)</span>
          </label>
          <input
            type="text"
            value={designerFigmaKey}
            onChange={e => setDesignerFigmaKey(e.target.value)}
            placeholder="e.g. yO7V6x2VhxuIhDyR24fQ2h"
            style={{
              width: '100%', boxSizing: 'border-box',
              background: C.surface, border: `1px solid ${C.border}`,
              borderRadius: 8, padding: '9px 12px', color: C.text,
              fontSize: 13, fontFamily: 'Inter, system-ui, sans-serif', outline: 'none',
            }}
          />
          <div style={{ fontSize: 11, color: C.muted, marginTop: 5, lineHeight: 1.5 }}>
            Find it in your Figma URL: figma.com/design/<strong style={{ color: C.text }}>THIS_PART</strong>/your-file-name
          </div>
        </div>

        {primaryBtn('Next: Set up MCP →', () => setStep('d2'))}
      </div>
    </div>
  )

  // ─── Designer Step D2 — MCP setup ───────────────────────────────────────

  const mcpInstructions = `// Claude Code: add to ~/.claude.json → mcpServers
// Cursor: Settings → MCP Servers
// Claude Desktop: ~/Library/Application Support/Claude/claude_desktop_config.json

{
  "figma": {
    "command": "npx",
    "args": ["-y", "figma-developer-mcp", "--stdio"],
    "env": {
      "FIGMA_ACCESS_TOKEN": "your-figma-personal-access-token"
    }
  }
}

// Get your token:
// figma.com → Profile picture → Settings → Security → Personal access tokens`

  const StepD2 = () => (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <div><BackBtn to="d1" />
          <div style={{ fontSize: 14, fontWeight: 800, marginBottom: 3 }}>Connect AI tools to Figma</div>
          <div style={{ fontSize: 12, color: C.muted, lineHeight: 1.5 }}>The Figma MCP lets Cursor and Claude read your components and create new ones directly in your file.</div>
        </div>
        <CloseBtn />
      </div>
      <Progress total={3} current={2} />
      <div style={{ ...bodyStyle, display: 'flex', flexDirection: 'column', gap: 12 }}>
        <div style={{ fontSize: 12, fontWeight: 700, color: C.text }}>What you get with MCP connected:</div>
        <div style={{
          display: 'flex', flexDirection: 'column', gap: 8,
          fontSize: 11, color: C.muted, lineHeight: 1.6,
        }}>
          {[
            '◈  AI can read your Figma components as context when vibe-coding',
            '✦  When Drift finds a gap, "Create in Figma" generates the component accurately using your real design tokens',
            '⟳  Changes flow: Figma → Storybook → AI builds with it → Drift measures it',
          ].map((line, i) => (
            <div key={i} style={{ background: C.surface, borderRadius: 8, padding: '8px 10px', border: `1px solid ${C.border}` }}>{line}</div>
          ))}
        </div>

        <div>
          <div style={{ fontSize: 11, fontWeight: 700, color: C.muted, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 }}>MCP config to add</div>
          <pre style={{
            background: C.surface, border: `1px solid ${C.border}`,
            borderRadius: 8, padding: '10px 12px', margin: 0,
            fontSize: 10, color: C.text, lineHeight: 1.6,
            fontFamily: 'monospace', overflowX: 'auto', whiteSpace: 'pre',
          }}>{mcpInstructions}</pre>
        </div>

        <button
          onClick={() => { navigator.clipboard.writeText(mcpInstructions); setMcpCopied(true); setTimeout(() => setMcpCopied(false), 2000) }}
          style={{
            background: mcpCopied ? C.green : C.surface,
            border: `1px solid ${mcpCopied ? C.green : C.border}`,
            borderRadius: 8, padding: '7px 14px',
            fontSize: 11, fontWeight: 600, color: mcpCopied ? '#fff' : C.text,
            cursor: 'pointer', fontFamily: 'Inter, system-ui, sans-serif',
            transition: 'all 0.2s',
          }}
        >{mcpCopied ? '✓ Copied!' : 'Copy MCP config'}</button>

        {primaryBtn('Next: Loop in your developer →', () => setStep('d3'))}
      </div>
    </div>
  )

  // ─── Designer Step D3 — Dev handoff ─────────────────────────────────────

  const handoffText = buildDevHandoff(designerFigmaKey)

  const StepD3 = () => (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <div><BackBtn to="d2" />
          <div style={{ fontSize: 14, fontWeight: 800, marginBottom: 3 }}>Loop in your developer</div>
          <div style={{ fontSize: 12, color: C.muted, lineHeight: 1.5 }}>Send this to your developer — they'll connect Storybook and set up the CI check. Takes them about 5 minutes.</div>
        </div>
        <CloseBtn />
      </div>
      <Progress total={3} current={3} />
      <div style={{ ...bodyStyle, display: 'flex', flexDirection: 'column', gap: 12 }}>
        <div style={{
          background: C.surface, border: `1px solid ${C.border}`,
          borderRadius: 8, padding: '12px 14px',
          fontSize: 11, color: C.text, lineHeight: 1.7,
          whiteSpace: 'pre-wrap', fontFamily: 'Inter, system-ui, sans-serif',
        }}>{handoffText}</div>

        <button
          onClick={() => { navigator.clipboard.writeText(handoffText); setHandoffCopied(true); setTimeout(() => setHandoffCopied(false), 2000) }}
          style={{
            background: handoffCopied ? C.green : C.blue,
            border: 'none', borderRadius: 8, padding: '8px 16px',
            fontSize: 12, fontWeight: 700, color: '#fff',
            cursor: 'pointer', fontFamily: 'Inter, system-ui, sans-serif',
            transition: 'background 0.2s',
          }}
        >{handoffCopied ? '✓ Copied to clipboard!' : 'Copy message for developer'}</button>

        <div style={{ fontSize: 11, color: C.muted, lineHeight: 1.6, padding: '8px 10px', background: C.surface, borderRadius: 8, border: `1px solid ${C.border}` }}>
          Once your developer connects Storybook, Drift will automatically post coverage scores on every PR — you'll see exactly which AI-generated components aren't from the design system.
        </div>

        <button onClick={onDone} style={{
          background: 'none', border: `1px solid ${C.border}`,
          borderRadius: 8, padding: '7px 14px',
          fontSize: 11, fontWeight: 600, color: C.muted,
          cursor: 'pointer', fontFamily: 'Inter, system-ui, sans-serif',
        }}>Done — explore Drift</button>
      </div>
    </div>
  )

  // ─── Developer Step 2 — Multi-source selector ───────────────────────────

  const SOURCE_OPTIONS: Array<{ key: DSSource; icon: string; color: string; title: string; sub: string }> = [
    { key: 'figma',     icon: '◈', color: C.purple, title: 'Figma',          sub: 'My team designs components there — some or all pages' },
    { key: 'storybook', icon: '📖', color: C.blue,   title: 'Storybook',      sub: 'We have a component catalog (complete, partial, or not sure)' },
    { key: 'package',   icon: '📦', color: C.green,  title: 'Code package',   sub: 'Components live in an npm package or a local folder' },
    { key: 'fresh',     icon: '✦', color: C.amber,  title: 'Building it',    sub: 'No formal DS yet — Drift will track what we build and suggest what to standardize' },
  ]

  const canContinue = sources.size > 0
  const nextStep = (): WizardStep => {
    if (sources.has('figma')) return 'figma'
    if (sources.has('storybook')) return 'sb'
    if (sources.has('package')) return 4
    return 4  // fresh: straight to export with empty config
  }

  const Step2 = () => (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <div><BackBtn to={1} />
          <div style={{ fontSize: 14, fontWeight: 800, marginBottom: 3 }}>Where is your design system?</div>
          <div style={{ fontSize: 12, color: C.muted, lineHeight: 1.5 }}>Select everything that applies — Drift works with whatever you have.</div>
        </div>
        <CloseBtn />
      </div>
      <div style={{ ...bodyStyle, display: 'flex', flexDirection: 'column', gap: 8 }}>

        {SOURCE_OPTIONS.map(opt => {
          const active = sources.has(opt.key)
          return (
            <button
              key={opt.key}
              onClick={() => toggleSource(opt.key)}
              style={{
                background: active ? `${opt.color}10` : C.surface,
                border: `1px solid ${active ? opt.color : C.border}`,
                borderRadius: 10, padding: '12px 14px', cursor: 'pointer',
                textAlign: 'left', fontFamily: 'Inter, system-ui, sans-serif',
                transition: 'all 0.15s', display: 'flex', alignItems: 'flex-start', gap: 10,
              }}
            >
              <div style={{
                width: 28, height: 28, borderRadius: 8, flexShrink: 0,
                background: active ? `${opt.color}20` : C.surface2,
                border: `1px solid ${active ? opt.color : C.border}`,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 14, color: active ? opt.color : C.muted,
                transition: 'all 0.15s',
              }}>{opt.icon}</div>
              <div>
                <div style={{ fontSize: 13, fontWeight: 700, color: active ? opt.color : C.text, marginBottom: 2 }}>{opt.title}</div>
                <div style={{ fontSize: 11, color: C.muted, lineHeight: 1.5 }}>{opt.sub}</div>
              </div>
              <div style={{
                marginLeft: 'auto', width: 16, height: 16, borderRadius: '50%', flexShrink: 0,
                background: active ? opt.color : 'none',
                border: `2px solid ${active ? opt.color : C.border}`,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 9, color: '#fff', transition: 'all 0.15s',
              }}>{active ? '✓' : ''}</div>
            </button>
          )
        })}

        <div style={{ paddingTop: 4 }}>
          {primaryBtn('Continue →', () => setStep(nextStep()), !canContinue)}
        </div>

        <button onClick={() => setStep('manual')} style={{
          background: 'none', border: 'none', cursor: 'pointer', padding: '2px 0',
          fontSize: 11, color: C.muted, fontFamily: 'Inter, system-ui, sans-serif', textAlign: 'center',
        }}>
          I'll type my component names in myself →
        </button>
      </div>
    </div>
  )

  // ─── Developer Step Figma — Figma details ───────────────────────────────

  const StepFigma = () => (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <div><BackBtn to={2} />
          <div style={{ fontSize: 14, fontWeight: 800, marginBottom: 3 }}>Connect your Figma</div>
          <div style={{ fontSize: 12, color: C.muted, lineHeight: 1.5 }}>Drift reads your published components directly — no manual list.</div>
        </div>
        <CloseBtn />
      </div>
      <div style={{ ...bodyStyle, display: 'flex', flexDirection: 'column', gap: 14 }}>

        <div>
          <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: C.muted, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 }}>
            Figma file key or URL
          </label>
          <input type="text" value={figmaKey} onChange={e => setFigmaKey(e.target.value)}
            placeholder="yO7V6x2VhxuIhDyR24fQ2h  or  figma.com/design/..."
            style={{ width: '100%', boxSizing: 'border-box', background: C.surface, border: `1px solid ${C.border}`, borderRadius: 8, padding: '9px 12px', color: C.text, fontSize: 13, fontFamily: 'Inter, system-ui, sans-serif', outline: 'none' }}
          />
          <div style={{ fontSize: 11, color: C.muted, marginTop: 5 }}>
            In your Figma URL: figma.com/design/<strong style={{ color: C.text }}>THIS_PART</strong>/your-file
          </div>
        </div>

        <div>
          <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: C.muted, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 }}>
            Personal access token <span style={{ fontWeight: 400, textTransform: 'none' }}>(stored in your browser only, never shared)</span>
          </label>
          <input type="password" value={figmaToken} onChange={e => { setFigmaToken(e.target.value); localStorage.setItem('drift-figma-token', e.target.value) }}
            placeholder="figd_..."
            style={{ width: '100%', boxSizing: 'border-box', background: C.surface, border: `1px solid ${C.border}`, borderRadius: 8, padding: '9px 12px', color: C.text, fontSize: 13, fontFamily: 'Inter, system-ui, sans-serif', outline: 'none' }}
          />
          <div style={{ fontSize: 11, color: C.muted, marginTop: 5, lineHeight: 1.6 }}>
            Get one at: figma.com → Profile → Settings → Security → Personal access tokens
          </div>
        </div>

        <div>
          <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: C.muted, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 }}>
            Which pages have your components? <span style={{ fontWeight: 400, textTransform: 'none' }}>(optional)</span>
          </label>
          <input type="text" value={figmaPages} onChange={e => setFigmaPages(e.target.value)}
            placeholder="Components, Design System, UI Kit (or leave blank for all pages)"
            style={{ width: '100%', boxSizing: 'border-box', background: C.surface, border: `1px solid ${C.border}`, borderRadius: 8, padding: '9px 12px', color: C.text, fontSize: 13, fontFamily: 'Inter, system-ui, sans-serif', outline: 'none' }}
          />
        </div>

        <div>
          <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: C.muted, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5 }}>
            How complete is your Figma library?
          </label>
          {([
            { val: 'full',    label: 'It\'s our full component library — everything DS is there' },
            { val: 'partial', label: 'It has most components but not everything' },
            { val: 'unsure',  label: 'It\'s kind of a mix / I\'m not fully sure what\'s there' },
          ] as const).map(opt => (
            <label key={opt.val} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6, cursor: 'pointer' }}>
              <input type="radio" name="figmaCompletion" value={opt.val}
                checked={figmaCompletion === opt.val}
                onChange={() => setFigmaCompletion(opt.val)}
                style={{ accentColor: C.purple }}
              />
              <span style={{ fontSize: 12, color: C.text }}>{opt.label}</span>
            </label>
          ))}
        </div>

        {sources.has('package') && (
          <div>
            <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: C.muted, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 }}>
              Also: your code package
            </label>
            <input type="text" value={dsPackage} onChange={e => setDsPackage(e.target.value)}
              placeholder="@acme/ui  or  ./src/components"
              style={{ width: '100%', boxSizing: 'border-box', background: C.surface, border: `1px solid ${C.border}`, borderRadius: 8, padding: '9px 12px', color: C.text, fontSize: 13, fontFamily: 'Inter, system-ui, sans-serif', outline: 'none' }}
            />
          </div>
        )}

        {primaryBtn(
          sources.has('storybook') ? 'Next: Storybook →' : 'Generate my config →',
          () => sources.has('storybook') ? setStep('sb') : setStep(4),
          !figmaKey.trim()
        )}
      </div>
    </div>
  )

  // ─── Developer Step SB — Storybook URL (secondary path) ─────────────────

  const StepSB = () => (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <div><BackBtn to={2} />
          <div style={{ fontSize: 14, fontWeight: 800, marginBottom: 3 }}>Connect Storybook</div>
          <div style={{ fontSize: 12, color: C.muted, lineHeight: 1.5 }}>Drift fetches your story index so you can pick which components are part of your design system.</div>
        </div>
        <CloseBtn />
      </div>
      <div style={{ ...bodyStyle, display: 'flex', flexDirection: 'column', gap: 12 }}>
        <div>
          <label style={{ display: 'block', fontSize: 11, fontWeight: 700, color: C.muted, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 }}>
            Storybook URL
          </label>
          <input
            type="text"
            value={sbUrl}
            onChange={e => { setSbUrl(e.target.value); setFetchErr(null) }}
            onKeyDown={e => e.key === 'Enter' && handleDiscover()}
            placeholder="http://localhost:6006"
            style={{
              width: '100%', boxSizing: 'border-box',
              background: C.surface, border: `1px solid ${fetchErr ? C.red : C.border}`,
              borderRadius: 8, padding: '9px 12px', color: C.text,
              fontSize: 13, fontFamily: 'Inter, system-ui, sans-serif', outline: 'none',
            }}
          />
          <div style={{ fontSize: 11, color: C.muted, marginTop: 5, lineHeight: 1.5 }}>
            Runs on port 6006 by default (<code style={{ fontFamily: 'monospace' }}>npm run storybook</code>).
          </div>
          {fetchErr && (
            <div style={{ fontSize: 11, color: C.red, marginTop: 6, lineHeight: 1.5 }}>
              {fetchErr}
              <button onClick={() => setStep('manual')} style={{
                display: 'block', marginTop: 8, background: 'none', border: 'none',
                color: C.blue, fontSize: 11, fontWeight: 600, cursor: 'pointer',
                padding: 0, fontFamily: 'Inter, system-ui, sans-serif', textDecoration: 'underline',
              }}>
                Enter components manually instead →
              </button>
            </div>
          )}
        </div>

        <label style={{ display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer' }}>
          <input type="checkbox" checked={hasFigmaMcp} onChange={e => setHasFigmaMcp(e.target.checked)}
            style={{ accentColor: C.purple, width: 14, height: 14, flexShrink: 0 }} />
          <div>
            <div style={{ fontSize: 12, fontWeight: 600, color: C.text }}>I have Figma MCP connected</div>
            <div style={{ fontSize: 11, color: C.muted }}>Enables AI to read/write Figma directly.</div>
          </div>
        </label>

        <div style={{ display: 'flex', gap: 8 }}>
          {primaryBtn(fetching ? 'Loading…' : 'Load my components', handleDiscover, fetching)}
        </div>
        {fetching && (
          <div style={{ fontSize: 11, color: C.muted, display: 'flex', alignItems: 'center', gap: 6 }}>
            <div style={{ width: 10, height: 10, borderRadius: '50%', border: `2px solid ${C.blue}`, borderTopColor: 'transparent', animation: 'spin 0.8s linear infinite' }} />
            Fetching story index…
          </div>
        )}
      </div>
    </div>
  )

  // ─── Developer Step 3 — Select components ──────────────────────────────

  const allSelected = discovered.length > 0 && selected.size === discovered.length
  const toggleAll = () => { if (allSelected) setSelected(new Set()); else setSelected(new Set(discovered.map(c => c.displayName))) }
  const toggleOne = (name: string) => { setSelected(prev => { const next = new Set(prev); next.has(name) ? next.delete(name) : next.add(name); return next }) }
  const selectedComponents = discovered.filter(c => selected.has(c.displayName))

  const Step3 = () => (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <div><BackBtn to={2} />
          <div style={{ fontSize: 14, fontWeight: 800, marginBottom: 3 }}>Which are your DS components?</div>
          <div style={{ fontSize: 12, color: C.muted }}>Discovered {discovered.length} from Storybook — select the ones that are part of your design system.</div>
        </div>
        <CloseBtn />
      </div>
      <Progress total={4} current={3} />
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 14px', borderBottom: `1px solid ${C.border}`, flexShrink: 0 }}>
        <span style={{ fontSize: 11, color: C.muted }}>{selected.size} of {discovered.length} selected</span>
        <button onClick={toggleAll} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 11, color: C.blue, fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, padding: 0 }}>
          {allSelected ? 'Deselect all' : 'Select all'}
        </button>
      </div>
      <div style={{ flex: 1, overflowY: 'auto', padding: '6px 0' }}>
        {discovered.map(c => (
          <label key={c.displayName} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '7px 14px', cursor: 'pointer', borderBottom: `1px solid ${C.border}` }}>
            <input type="checkbox" checked={selected.has(c.displayName)} onChange={() => toggleOne(c.displayName)} style={{ accentColor: C.blue, width: 14, height: 14, flexShrink: 0 }} />
            <div>
              <div style={{ fontSize: 12, fontWeight: 600, color: C.text }}>{c.displayName}</div>
              <div style={{ fontSize: 10, color: C.muted, marginTop: 1 }}>{c.storyPath}</div>
            </div>
          </label>
        ))}
      </div>
      <div style={{ padding: '10px 14px', borderTop: `1px solid ${C.border}`, flexShrink: 0 }}>
        {primaryBtn(`Continue (${selected.size} selected) →`, () => setStep(4), selected.size === 0)}
      </div>
    </div>
  )

  // ─── Developer Step 4 — Export ──────────────────────────────────────────

  const handleCopyConfig = async () => {
    const text = buildConfigSnippet(sbUrl, chromaticUrl, figmaKey, jiraBaseUrl, jiraProjectKey, selectedComponents)
    try { await navigator.clipboard.writeText(text) } catch { prompt('Copy config:', text) }
    setConfigCopied(true); setTimeout(() => setConfigCopied(false), 2000)
  }
  const handleCopyClaude = async () => {
    const text = buildClaudeContent(selectedComponents, sbUrl, chromaticUrl, figmaKey, hasFigmaMcp)
    try { await navigator.clipboard.writeText(text) } catch { prompt('Copy CLAUDE.md:', text) }
    setClaudeCopied(true); setTimeout(() => setClaudeCopied(false), 2000)
  }

  const configSnippet = buildConfigSnippet(
    chromaticUrl || sbUrl,
    chromaticUrl,
    figmaKey,
    jiraBaseUrl,
    jiraProjectKey,
    selectedComponents,
    dsPackage || undefined,
  )
  const claudeContent = buildClaudeContent(selectedComponents, sbUrl, chromaticUrl, figmaKey, hasFigmaMcp)

  const Step4 = () => (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <div>
          <div style={{ fontSize: 15, fontWeight: 800, marginBottom: 3 }}>You're all set! 🎉</div>
          <div style={{ fontSize: 12, color: C.muted, lineHeight: 1.5 }}>Copy these into your project to activate Drift.</div>
        </div>
        <CloseBtn />
      </div>
      <Progress total={3} current={3} />
      {dsPackage && (
        <div style={{ padding: '8px 14px', background: `${C.green}10`, borderBottom: `1px solid ${C.border}`, flexShrink: 0, fontSize: 11, color: C.green, lineHeight: 1.6 }}>
          After pasting this config, run <code style={{ fontFamily: 'monospace', background: `${C.green}20`, padding: '1px 5px', borderRadius: 4 }}>npm run drift-sync</code> — it scans your code and fills in your components automatically.
        </div>
      )}
      <div style={{ padding: '8px 14px', borderBottom: `1px solid ${C.border}`, flexShrink: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
        <div>
          <label style={{ display: 'block', fontSize: 10, fontWeight: 700, color: C.muted, marginBottom: 4, textTransform: 'uppercase', letterSpacing: 0.4 }}>Figma file key</label>
          <input type="text" value={figmaKey} onChange={e => setFigmaKey(e.target.value)} placeholder="e.g. yO7V6x2VhxuIhDyR24fQ2h" style={{ width: '100%', boxSizing: 'border-box', background: C.surface, border: `1px solid ${C.border}`, borderRadius: 6, padding: '7px 10px', color: C.text, fontSize: 12, fontFamily: 'Inter, system-ui, sans-serif', outline: 'none' }} />
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <div style={{ flex: 2 }}>
            <label style={{ display: 'block', fontSize: 10, fontWeight: 700, color: C.muted, marginBottom: 4, textTransform: 'uppercase', letterSpacing: 0.4 }}>Jira base URL</label>
            <input type="text" value={jiraBaseUrl} onChange={e => setJiraBaseUrl(e.target.value)} placeholder="https://company.atlassian.net" style={{ width: '100%', boxSizing: 'border-box', background: C.surface, border: `1px solid ${C.border}`, borderRadius: 6, padding: '7px 10px', color: C.text, fontSize: 12, fontFamily: 'Inter, system-ui, sans-serif', outline: 'none' }} />
          </div>
          <div style={{ flex: 1 }}>
            <label style={{ display: 'block', fontSize: 10, fontWeight: 700, color: C.muted, marginBottom: 4, textTransform: 'uppercase', letterSpacing: 0.4 }}>Project key</label>
            <input type="text" value={jiraProjectKey} onChange={e => setJiraProjectKey(e.target.value)} placeholder="DS" style={{ width: '100%', boxSizing: 'border-box', background: C.surface, border: `1px solid ${C.border}`, borderRadius: 6, padding: '7px 10px', color: C.text, fontSize: 12, fontFamily: 'Inter, system-ui, sans-serif', outline: 'none' }} />
          </div>
        </div>
      </div>
      <div style={{ display: 'flex', borderBottom: `1px solid ${C.border}`, flexShrink: 0 }}>
        {(['config', 'claude'] as ExportTab[]).map(t => (
          <button key={t} onClick={() => setActiveTab(t)} style={{ flex: 1, padding: '8px 0', background: 'none', border: 'none', cursor: 'pointer', fontSize: 11, fontWeight: 700, color: activeTab === t ? C.blue : C.muted, borderBottom: `2px solid ${activeTab === t ? C.blue : 'transparent'}`, fontFamily: 'Inter, system-ui, sans-serif', transition: 'color 0.15s' }}>
            {t === 'config' ? 'config.ts' : 'CLAUDE.md'}
          </button>
        ))}
      </div>
      <div style={{ flex: 1, overflowY: 'auto', padding: '10px 14px', display: 'flex', flexDirection: 'column', gap: 8 }}>
        <pre style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: 8, padding: '10px', margin: 0, fontSize: 10.5, color: C.text, lineHeight: 1.6, fontFamily: 'monospace', overflowX: 'auto', whiteSpace: 'pre', flex: 1 }}>
          {activeTab === 'config' ? configSnippet : claudeContent}
        </pre>
        <button onClick={activeTab === 'config' ? handleCopyConfig : handleCopyClaude} style={{ background: (activeTab === 'config' ? configCopied : claudeCopied) ? C.green : C.blue, color: '#fff', border: 'none', borderRadius: 8, padding: '8px 14px', fontSize: 12, fontWeight: 700, cursor: 'pointer', fontFamily: 'Inter, system-ui, sans-serif', transition: 'background 0.2s', flexShrink: 0 }}>
          {(activeTab === 'config' ? configCopied : claudeCopied) ? 'Copied!' : `Copy ${activeTab === 'config' ? 'config.ts' : 'CLAUDE.md'}`}
        </button>
        <button onClick={onDone} style={{ background: 'none', border: `1px solid ${C.border}`, borderRadius: 8, padding: '7px 14px', fontSize: 11, fontWeight: 600, color: C.muted, cursor: 'pointer', fontFamily: 'Inter, system-ui, sans-serif' }}>
          Done — open Drift panel
        </button>
      </div>
    </div>
  )

  // ─── Manual entry ───────────────────────────────────────────────────────

  const ManualStep = () => {
    const names = manualText.split(/[\n,]+/).map(s => s.trim()).filter(Boolean)
    const valid = names.length > 0
    const handleConfirm = () => {
      const comps: DiscoveredComponent[] = names.map(n => ({ displayName: n, storyPath: n.toLowerCase().replace(/\s+/g, '-') + '--default' }))
      setDiscovered(comps); setSelected(new Set(comps.map(c => c.displayName))); setStep(4)
    }
    return (
      <div style={panelStyle}>
        <div style={headerStyle}>
          <div><BackBtn to={1} />
            <div style={{ fontSize: 14, fontWeight: 800, marginBottom: 3 }}>Enter components manually</div>
            <div style={{ fontSize: 12, color: C.muted, lineHeight: 1.5 }}>One name per line — use exact React display names (same as React DevTools).</div>
          </div>
          <CloseBtn />
        </div>
        <div style={{ ...bodyStyle, display: 'flex', flexDirection: 'column', gap: 12 }}>
          <textarea value={manualText} onChange={e => setManualText(e.target.value)} placeholder={'Button\nModal\nNavbar\nTenantsTable\n...'} rows={8} style={{ width: '100%', boxSizing: 'border-box', resize: 'vertical', background: C.surface, border: `1px solid ${C.border}`, borderRadius: 8, padding: '10px 12px', color: C.text, fontSize: 12, fontFamily: 'monospace', lineHeight: 1.7, outline: 'none' }} />
          {valid && <div style={{ fontSize: 11, color: C.muted }}>{names.length} component{names.length !== 1 ? 's' : ''} — storyPaths will be best-guess placeholders.</div>}
          {primaryBtn(`Generate config for ${valid ? names.length : '…'} components →`, handleConfirm, !valid)}
        </div>
      </div>
    )
  }

  // ─── Render ─────────────────────────────────────────────────────────────

  return (
    <>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      {step === 1        && <Step1 />}
      {step === 2        && <Step2 />}
      {step === 'figma'  && <StepFigma />}
      {step === 'sb'     && <StepSB />}
      {step === 3        && <Step3 />}
      {step === 4        && <Step4 />}
      {step === 'manual' && <ManualStep />}
      {step === 'd1'     && <StepD1 />}
      {step === 'd2'     && <StepD2 />}
      {step === 'd3'     && <StepD3 />}
    </>
  )
}
