import type { Meta, StoryObj } from '@storybook/react'
import { BulkPaymentScreen } from './BulkPaymentScreen'

const meta: Meta<typeof BulkPaymentScreen> = {
  title: 'Prototypes/Bulk Payment Screen',
  component: BulkPaymentScreen,
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: `
**DS Coverage: 93%** (15/16 elements from DS)

Generated by \`/drift-scaffold\` — uses only StorageOS DS components.

### Gap
- \`BulkActionBar\` — multi-select action toolbar. Pending Figma spec.
  Run \`/drift-push request BulkActionBar "Multi-select action toolbar for list screens"\` to file the design request.

### DS components used
Navbar, Sidebar, KPICard ×3, Tabs, Modal, Toast, Badge, Input, Dropdown, Button,
TenantsTable, TenantPageHeader, PaymentBanner, TenantInfoCard, UnitDetailsCard,
CommunicationsPanel, PinnedNotes
        `,
      },
    },
  },
}

export default meta

type Story = StoryObj<typeof BulkPaymentScreen>

export const Default: Story = {}
