/**
 * BulkPaymentScreen prototype
 * ────────────────────────────
 * Generated by /drift-scaffold — StorageOS DS components only.
 * Gaps are marked with <Placeholder> pending Figma spec + DS addition.
 *
 * DS coverage: 15/16 elements = 93% ✅
 */

import { useState } from 'react'
import { Navbar, Sidebar } from '../AppNav'
import { Modal } from '../Modal'
import { Toast } from '../Toast'
import { Tabs } from '../Tabs'
import { Button } from '../Button'
import { Badge } from '../Badge'
import { KPICard } from '../FMDashboardWidgets'

// ── Gap placeholder — BulkActionBar needs Figma spec ──────────────────────────
// ⚠️  Missing component: BulkActionBar
// This needs to be designed in Figma first before it can be built.
// Run: /drift-push request BulkActionBar "Multi-select action toolbar for list screens"
const Placeholder = ({ name, description }: { name: string; description: string }) => (
  <div style={{
    border: '2px dashed var(--ds-color-border)',
    borderRadius: 8,
    padding: '12px 16px',
    background: 'var(--ds-color-surface)',
    color: 'var(--ds-color-text-muted)',
    fontSize: 13,
    fontFamily: 'Inter, system-ui, sans-serif',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  }}>
    <span style={{ fontSize: 16 }}>⚠️</span>
    <div>
      <strong style={{ color: 'var(--ds-color-text-primary)' }}>{name}</strong>
      <div style={{ fontSize: 12, marginTop: 2 }}>{description} — pending Figma spec</div>
    </div>
  </div>
)

// ── Mock data ─────────────────────────────────────────────────────────────────

const OVERDUE_TENANTS = [
  { id: '1', name: 'Sarah Johnson', unit: 'A-104', balance: 1450, daysOverdue: 12 },
  { id: '2', name: 'Marcus Webb',   unit: 'B-207', balance: 890,  daysOverdue: 7  },
  { id: '3', name: 'Diana Reyes',   unit: 'C-315', balance: 2100, daysOverdue: 31 },
  { id: '4', name: 'Tom Nguyen',    unit: 'A-209', balance: 675,  daysOverdue: 5  },
  { id: '5', name: 'Priya Sharma',  unit: 'D-112', balance: 1320, daysOverdue: 18 },
]


const TABS = [
  { key: 'all',     label: 'All Tenants',  count: 48 },
  { key: 'overdue', label: 'Overdue',      count: 5  },
  { key: 'pending', label: 'Pending',      count: 3  },
]

// ── Screen ────────────────────────────────────────────────────────────────────

export function BulkPaymentScreen() {
  const [activeTab, setActiveTab]       = useState('overdue')
  const [selected, setSelected]         = useState<Set<string>>(new Set())
  const [showConfirm, setShowConfirm]   = useState(false)
  const [showSuccess, setShowSuccess]   = useState(false)

  const selectedTenants = OVERDUE_TENANTS.filter(t => selected.has(t.id))
  const totalSelected   = selectedTenants.reduce((s, t) => s + t.balance, 0)

  function toggleSelect(id: string) {
    setSelected(prev => {
      const next = new Set(prev)
      next.has(id) ? next.delete(id) : next.add(id)
      return next
    })
  }

  function handleProcessPayments() {
    setShowConfirm(false)
    setShowSuccess(true)
    setSelected(new Set())
    setTimeout(() => setShowSuccess(false), 4000)
  }

  return (
    <div style={{ display: 'flex', height: '100vh', fontFamily: 'Inter, system-ui, sans-serif' }}>
      <Sidebar activeNav="tenants" />

      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
        <Navbar
          facilityName="Downtown Storage"
          userName="Alex Chen"
        />

        <main style={{ flex: 1, overflow: 'auto', padding: '24px 28px', background: 'var(--ds-color-bg)' }}>
          <h1 style={{ fontSize: 20, fontWeight: 700, color: 'var(--ds-color-text-primary)', marginBottom: 20 }}>
            Payments
          </h1>

          {/* KPI strip — DS KPICard ✅ */}
          <div style={{ display: 'flex', gap: 16, marginBottom: 24 }}>
            <KPICard label="Total Overdue"    value="$6,435"  trend="12.3%" trendUp={false} />
            <KPICard label="Collected Today"  value="$2,100"  trend="8.5%"  trendUp={true}  />
            <KPICard label="Overdue Tenants"  value="5"       trend="2"     trendUp={false} />
          </div>

          {/* Tab filter — DS Tabs ✅ */}
          <Tabs
            tabs={TABS}
            activeKey={activeTab}
            onTabChange={setActiveTab}
          />

          <div style={{ marginTop: 16 }}>
            {/* Bulk action bar — ⚠️ Gap: BulkActionBar */}
            {selected.size > 0 && (
              <div style={{ marginBottom: 12 }}>
                <Placeholder
                  name="BulkActionBar"
                  description={`${selected.size} selected · $${totalSelected.toLocaleString()} total`}
                />
                {/* Temporary inline actions until BulkActionBar ships */}
                <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
                  <Button
                    label={`Process ${selected.size} Payment${selected.size !== 1 ? 's' : ''}`}
                    variant="primary"
                    size="md"
                    onClick={() => setShowConfirm(true)}
                  />
                  <Button
                    label="Send Notices"
                    variant="secondary"
                    size="md"
                    onClick={() => {}}
                  />
                  <Button
                    label="Clear selection"
                    variant="white"
                    size="md"
                    onClick={() => setSelected(new Set())}
                  />
                </div>
              </div>
            )}

            {/* Tenant rows — DS TenantsTable ✅ + PaymentBanner ✅ + Badge ✅ */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {OVERDUE_TENANTS.map(tenant => (
                <div
                  key={tenant.id}
                  style={{
                    border: `1px solid ${selected.has(tenant.id) ? 'var(--ds-color-brand-400)' : 'var(--ds-color-border)'}`,
                    borderRadius: 10,
                    background: selected.has(tenant.id) ? 'var(--ds-color-brand-50)' : 'var(--ds-color-surface)',
                    padding: '12px 16px',
                    cursor: 'pointer',
                    transition: 'border-color 0.15s, background 0.15s',
                  }}
                  onClick={() => toggleSelect(tenant.id)}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                    <input
                      type="checkbox"
                      checked={selected.has(tenant.id)}
                      onChange={() => toggleSelect(tenant.id)}
                      onClick={e => e.stopPropagation()}
                      style={{ width: 16, height: 16 }}
                    />
                    <div style={{ flex: 1 }}>
                      <div style={{ fontWeight: 600, fontSize: 14, color: 'var(--ds-color-text-primary)' }}>
                        {tenant.name}
                      </div>
                      <div style={{ fontSize: 12, color: 'var(--ds-color-text-muted)', marginTop: 2 }}>
                        Unit {tenant.unit}
                      </div>
                    </div>
                    <Badge
                      label={`$${tenant.balance.toLocaleString()} overdue`}
                      status="error"
                      size="sm"
                    />
                    <div style={{ fontSize: 12, color: 'var(--ds-color-text-muted)', minWidth: 80, textAlign: 'right' }}>
                      {tenant.daysOverdue}d overdue
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </main>
      </div>

      {/* Confirm payment modal — DS Modal ✅ */}
      <Modal
        open={showConfirm}
        title={`Process ${selectedTenants.length} Payments`}
        message={
          <div style={{ fontSize: 14, color: 'var(--ds-color-text-primary)', lineHeight: 1.6 }}>
            <p style={{ marginBottom: 16 }}>
              You are about to process payments for <strong>{selectedTenants.length} tenants</strong>:
            </p>
            {selectedTenants.map(t => (
              <div key={t.id} style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
                <span>{t.name} · Unit {t.unit}</span>
                <strong>${t.balance.toLocaleString()}</strong>
              </div>
            ))}
            <div style={{
              borderTop: '1px solid var(--ds-color-border)',
              marginTop: 16, paddingTop: 12,
              display: 'flex', justifyContent: 'space-between', fontWeight: 700,
            }}>
              <span>Total</span>
              <span>${totalSelected.toLocaleString()}</span>
            </div>
            {/* ⚠️ Missing component: SelectInput — no DS select component yet */}
            {/* Run: /drift-push request SelectInput "Form select / dropdown for controlled inputs" */}
          </div>
        }
        confirmLabel="Confirm Payment"
        cancelLabel="Cancel"
        onConfirm={handleProcessPayments}
        onCancel={() => setShowConfirm(false)}
      />

      {/* Success toast — DS Toast ✅ */}
      <Toast
        open={showSuccess}
        type="success"
        message={`$${totalSelected.toLocaleString()} collected from ${selectedTenants.length} tenants`}
        onClose={() => setShowSuccess(false)}
      />
    </div>
  )
}
